apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
      - with:
          content: This is created today for testing functional test
        uses: AutoTest.PublishEvidence.e2d4aee9-92d9-4e16-ae6a-ffbde9b7357f.Action
