apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
      - with:
          content: This is created today for testing functional test
        uses: AutoTest.PublishEvidence.f441030f-4384-4131-81e6-7a7a3eca4190.Action
