
  name: Test

  on:
    workflow_dispatch:
      inputs:
        ENV:
          description: 'Environment to run tests'
          required: true
          default: 'QA'
          type: choice
          options:
            - QA
            - STAGING
            - PROD
        TEST_ENV_VALUE:
          description: 'Test environment value'
          required: false
          default: 'test_value'
          type: string

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Print Environment
          run: |
            echo "Running Environment: ${{ inputs.ENV }}"

        - name: Print Property Value
          run: |
            echo "TEST_ENV_VALUE: ${{ inputs.TEST_ENV_VALUE }}"
